application: aio
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: static/js
  
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
- url: .*
  script: main.py
  secure: optional
  